env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - jest
  - '@typescript-eslint'
rules:
  'react/prop-types': 1
  'jsx-a11y/anchor-is-valid': 0
  'react/react-in-jsx-scope': 0
overrides:
  - files: ['**/*.tsx']
    rules:
      'react/prop-types': off
settings:
  react:
    version: detect
